import { Logo } from "@/Logo";
import {
	Footer,
	Header,
	LayoutCarbon,
	Menu,
} from "@aaronellington/standard-ui";
import type { Metadata } from "next";
import "./global.css";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
	title: "AdBrick",
	description: "Generated by create next app",
};

const menu = new Menu.Menu([
	{
		content: <>Downloads</>,
		to: "/downloads",
	},
	{
		content: <>Support</>,
		to: "/support",
	},
	{
		content: <>Privacy Policy</>,
		to: "/privacy",
	},
	{
		content: <>Source Code</>,
		to: "https://github.com/adbrick/extension",
	},
]);

export default function RootLayout({ children }: { children: JSX.Element }) {
	return (
		<html lang="en">
			<body>
				<LayoutCarbon
					header={
						<Header
							brand={{
								content: (
									<div className={styles.logo}>
										<Logo /> AdBrick
									</div>
								),
								to: "/",
							}}
							menu={menu}
						/>
					}
					footer={
						<Footer menu={menu}>
							<>&copy; {new Date().getFullYear()} AdBrick</>
						</Footer>
					}
				>
					{children}
				</LayoutCarbon>
			</body>
		</html>
	);
}
